AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "spec/**/*"
    - "Capfile"
    - "Rakefile"
    - "config.ru"
    - "bin/setup"
    - "config/**/*"
  DisplayCopNames: true

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Style/FrozenStringLiteralComment:
  Enabled: false
