Rails:
  Enabled: true
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "spec/**/*"
    - "Capfile"
    - "Rakefile"
    - "config.ru"

  DisplayCopNames: true
  RunRailsCops: true

Style/Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Style/FrozenStringLiteralComment:
  Enabled: false
